version: '3'
services:
  gateway:
    build: ./gateway
    restart: always
    env_file:
      - .env
    networks:
      - backend
    ports:
      - "${GATEWAY_SERVICE_PORT}:${GATEWAY_SERVICE_PORT}"

  user:
    build: ./user-platform
    restart: always
    env_file:
      - .env
    networks:
      - backend

  logger:
    build: ./logger
    restart: always
    env_file:
      - .env
    networks:
      - backend

  todo:
    build: ./todo-platform
    restart: always
    env_file:
      - .env
    networks:
      - backend

networks:
  backend:
    driver: bridge
