version: '3'
services:
  gateway:
    build: ./gateway
    restart: always
    hostname: gateway
    env_file:
      - .env
    networks:
      - backend
    links:
      - todo
      - notification
      - user
      - db
    ports:
      - ${GATEWAY_SERVICE_PORT}:${GATEWAY_SERVICE_PORT}
  user:
    build: ./user-platfrom
    restart: always
    hostname: user
    env_file:
      - .env
    networks:
      - backend
    links:
      - db
  notification:
    build: ./notification-platform
    restart: always
    hostname: notification
    env_file:
      - .env
    networks:
      - backend
  todo:
    build: ./todo-platform
    restart: always
    hostname: todo
    env_file:
      - .env
    networks:
      - backend
    links:
      - notification
      - user
      - db
  db:
    image: 'mongo:3.7'
    restart: always
    hostname: db
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - "./db/data/db-files:/data/db"
      - "./db/init/:/docker-entrypoint-initdb.d/"
    networks:
      - backend
    env_file:
      - .env
    ports:
      - ${MONGO_CONNECTION_PORT}:27017
networks:
  backend:
    driver: bridge