version: '3'
services:
  gateway:
    build: ./gateway
    restart: always
    hostname: gateway
    env_file:
      - .env
    networks:
      - backend
    links:
      - todo
      - logger
      - user
    ports:
      - ${GATEWAY_SERVICE_PORT}:${GATEWAY_SERVICE_PORT}
  user:
    build: ./user-platfrom
    restart: always
    hostname: user
    env_file:
      - .env
    networks:
      - backend
  logger:
    build: ./logger
    restart: always
    hostname: logger
    env_file:
      - .env
    networks:
      - backend
  todo:
    build: ./todo-platform
    restart: always
    hostname: todo
    env_file:
      - .env
    networks:
      - backend
    links:
      - logger
      - user
networks:
  backend:
    driver: bridge